/**
 * DatabaseSerializer — emits CDDAL text from a finalized Database.
 *
 * Ported from Cdd::Cddal::Serializer (lib/cdd/cddal/serializer.rb).
 * Walks entities in canonical order (value_lists, value_terms, units,
 * class tree, properties, relations, view_controls), resolving property
 * IDs back to their first registered alias so the output is readable.
 *
 * The AST-level serializer in `./Serializer.ts` handles pre-parsed
 * documents; this module is the Database → text counterpart.
 */

import { Database } from "../models/Database";
import { Entity } from "../models/Entity";
import { Klass } from "../models/Klass";
import { REGISTRY } from "../models/PropertyIds.generated";
import {
  REGISTRY as META_REGISTRY,
  metaClassForType,
} from "../models/MetaClasses.generated";
import { unwrapAndSplit } from "../models/StructuredValues";

const DEFAULT_METACLASS = META_REGISTRY.MDC_C002.irdi;
const HEADER = "# Generated by opencdd CDDAL DatabaseSerializer";

const UNQUOTED_VALUE_RE =
  /^(?:true|false|null|-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?|\d{4}-\d{2}-\d{2}|[0-9]+\/[0-9]+\/\/\/[A-Za-z0-9_]+(?:_[0-9]+)?#[A-Za-z0-9_]+|[A-Za-z_][A-Za-z0-9_]*#[A-Za-z0-9_]+(?:##[A-Za-z0-9_]+)?|[A-Za-z_][A-Za-z0-9_]*)$/;

export class DatabaseSerializer {
  constructor(readonly database: Database) {}

  toCddal(): string {
    const lines: string[] = [HEADER];
    this.emitDefaultAliases(lines);
    this.emitEntities(lines, "value_lists", this.database.valueLists());
    this.emitEntities(lines, "value_terms", this.database.valueTerms());
    this.emitEntities(lines, "units", this.database.units());
    this.emitClassTree(lines);
    this.emitRootedProperties(lines);
    this.emitEntities(lines, "relations", this.database.relations());
    this.emitEntities(lines, "view_controls", this.database.viewControls());
    return lines.join("\n") + "\n";
  }

  private emitDefaultAliases(lines: string[]): void {
    lines.push("");
    for (const entry of Object.values(REGISTRY)) {
      for (const alias of entry.aliases) {
        lines.push(`alias ${alias}: ${entry.id}`);
      }
    }
  }

  private emitEntities(
    lines: string[],
    _label: string,
    entities: readonly Entity[],
  ): void {
    if (entities.length === 0) return;
    const sorted = [...entities].sort((a, b) =>
      (a.code ?? "").localeCompare(b.code ?? ""),
    );
    lines.push("");
    for (const entity of sorted) {
      this.emitInstance(lines, entity);
    }
  }

  private emitClassTree(lines: string[]): void {
    const roots = [...this.database.rootClasses()].sort((a, b) =>
      (a.code ?? "").localeCompare(b.code ?? ""),
    );
    if (roots.length === 0) return;
    lines.push("");
    for (const root of roots) this.walkClass(root, lines);
  }

  private walkClass(klass: Klass, lines: string[]): void {
    this.emitInstance(lines, klass);
    const sortedChildren = [...klass.children].sort((a, b) =>
      (a.code ?? "").localeCompare(b.code ?? ""),
    );
    for (const child of sortedChildren) this.walkClass(child, lines);
  }

  private emitRootedProperties(lines: string[]): void {
    const emitted = new Set<string>();
    const classes = [...this.database.classes()].sort((a, b) =>
      (a.code ?? "").localeCompare(b.code ?? ""),
    );
    for (const klass of classes) {
      const props = [...this.database.propertiesOf(klass)].sort((a, b) =>
        (a.code ?? "").localeCompare(b.code ?? ""),
      );
      for (const prop of props) {
        const key = prop.irdi?.toString() ?? "";
        if (emitted.has(key)) continue;
        emitted.add(key);
        this.emitInstance(lines, prop);
      }
    }
    const unrooted = this.database
      .properties()
      .filter((p) => !emitted.has(p.irdi?.toString() ?? ""))
      .sort((a, b) => (a.code ?? "").localeCompare(b.code ?? ""));
    for (const prop of unrooted) this.emitInstance(lines, prop);
  }

  private emitInstance(lines: string[], entity: Entity): void {
    const name = symbolNameFor(entity);
    const meta = metaClassRefFor(entity);
    const body = emitProperties(entity);
    lines.push("");
    lines.push(`instance ${name} < ${meta} {`);
    for (const line of body) lines.push(`  ${line}`);
    lines.push("}");
  }
}

function emitProperties(entity: Entity): string[] {
  const out: string[] = [];
  entity.eachProperty((key, value) => {
    if (value === undefined || value === null) return;
    const s = String(value);
    if (s.length === 0) return;
    const base = key.replace(/\.\w+$/, "");
    const langMatch = key.match(/\.([a-zA-Z]{2,3}(?:-[A-Za-z0-9]+)?)$/);
    const lang = langMatch ? langMatch[1] : null;
    const alias = aliasForPropertyId(base);
    const displayKey = lang ? `${alias}.${lang}` : alias;
    out.push(`${displayKey}: ${formatValue(value)}`);
  });
  return out;
}

function aliasForPropertyId(propertyId: string): string {
  const entry = REGISTRY[propertyId];
  return entry?.aliases[0] ?? propertyId;
}

function formatValue(value: unknown): string {
  const s = String(value);
  if (isStringLiteral(s)) return quoteString(s);
  if (isSetLike(s)) return formatSet(s);
  return s;
}

function isStringLiteral(s: string): boolean {
  return !UNQUOTED_VALUE_RE.test(s);
}

function quoteString(s: string): string {
  const escaped = s
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t")
    .replace(/[\b]/g, "\\b")
    .replace(/\f/g, "\\f");
  return `"${escaped}"`;
}

function isSetLike(s: string): boolean {
  return s.startsWith("(") && s.endsWith(")");
}

function formatSet(s: string): string {
  const elements = unwrapAndSplit(s);
  return `{ ${elements.join(", ")} }`;
}

function symbolNameFor(entity: Entity): string {
  const code = entity.code;
  if (code && code.length > 0) return code;
  const preferred = entity.preferredName("en");
  if (!preferred) return "instance";
  const safe = preferred.replace(/[^A-Za-z0-9_]/g, "_").replace(/^(\d)/, "_$1");
  return safe.length === 0 ? "instance" : safe;
}

function metaClassRefFor(entity: Entity): string {
  const type = entity.type;
  if (type) {
    const code = metaClassForType(type);
    if (code) return code;
  }
  if (entity.metaClassIrdi) return entity.metaClassIrdi;
  console.warn(
    `DatabaseSerializer: entity ${entity.irdi?.toString() ?? "(no irdi)"} has no resolvable meta-class; falling back to ${DEFAULT_METACLASS}`,
  );
  return DEFAULT_METACLASS;
}
